name: state_city_population
description: Dart list of states and cities
version: 0.0.2
homepage: https://github.com/olimou/dart-brazil-state-city-population
author: Emerson Moura <olimou@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
